// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parity.Storage;

#nullable disable

namespace Parity.Storage.Migrations
{
    [DbContext(typeof(BaselineDbContext))]
    partial class BaselineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Parity.Storage.BaselineSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Parity.Storage.StoredDiff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignLayer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Expected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Diffs");
                });

            modelBuilder.Entity("Parity.Storage.StoredDiff", b =>
                {
                    b.HasOne("Parity.Storage.BaselineSnapshot", null)
                        .WithMany("Diffs")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parity.Storage.BaselineSnapshot", b =>
                {
                    b.Navigation("Diffs");
                });
#pragma warning restore 612, 618
        }
    }
}
