// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parity.Server.Data;

#nullable disable

namespace Parity.Server.Data.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260826064811_CompressRawReport")]
    partial class CompressRawReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Parity.Server.Data.Diff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Delta")
                        .HasColumnType("REAL");

                    b.Property<string>("DesignId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignLayer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Expected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PageResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Soft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Tolerance")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PageResultId");

                    b.ToTable("Diffs");
                });

            modelBuilder.Entity("Parity.Server.Data.PageResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Critical")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesignNodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Matched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxSeverity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Medium")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesWithDiffs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Serious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unmatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("PageResults");
                });

            modelBuilder.Entity("Parity.Server.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Parity.Server.Data.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GateFailed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawReportGzip")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("Parity.Server.Data.Diff", b =>
                {
                    b.HasOne("Parity.Server.Data.PageResult", "PageResult")
                        .WithMany("Diffs")
                        .HasForeignKey("PageResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageResult");
                });

            modelBuilder.Entity("Parity.Server.Data.PageResult", b =>
                {
                    b.HasOne("Parity.Server.Data.Run", "Run")
                        .WithMany("Pages")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Parity.Server.Data.Run", b =>
                {
                    b.HasOne("Parity.Server.Data.Project", "Project")
                        .WithMany("Runs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Parity.Server.Data.PageResult", b =>
                {
                    b.Navigation("Diffs");
                });

            modelBuilder.Entity("Parity.Server.Data.Project", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Parity.Server.Data.Run", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
